"use client";
import Link from "next/link";
import { FormEvent, use, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/browser";

type Code = { id: string; short_code: string; business_name: string | null; target_url: string | null; status: "unassigned" | "active" | "disabled" };
type Event = { id: string; scanned_at: string; user_agent: string | null };
export default function CodeDetail({ params }: { params: Promise<{ id: string }> }) { const { id } = use(params); const [code, setCode] = useState<Code | null>(null); const [events, setEvents] = useState<Event[]>([]); const [saved, setSaved] = useState("");
  useEffect(() => { const client = createClient(); client.from("qr_codes").select("*").eq("id", id).single().then(({ data }) => setCode(data)); client.from("scan_events").select("id,scanned_at,user_agent").eq("qr_code_id", id).order("scanned_at", { ascending: false }).then(({ data }) => setEvents(data ?? [])); }, [id]);
  if (!code) return <div className="p-10 text-sm text-[var(--muted)]">Loading code...</div>;
  const loadedCode = code;
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const update = { business_name: String(form.get("business_name") || "") || null, target_url: String(form.get("target_url") || "") || null, status: form.get("status") as Code["status"] }; const { error } = await createClient().from("qr_codes").update(update).eq("id", loadedCode.id); setSaved(error ? error.message : "Changes saved."); if (!error) setCode({ ...loadedCode, ...update }); }
  return <div className="p-6 md:p-10"><Link href="/admin" className="text-sm text-[var(--muted)] underline">← Inventory</Link><header className="mb-10 mt-8 flex items-end justify-between gap-4"><div><p className="mono mb-3 text-xs text-[var(--muted)]">CODE DETAIL</p><h1 className="mono text-4xl font-semibold">{code.short_code}</h1></div><span className="mono text-sm text-[var(--muted)]">{events.length} scans</span></header><div className="grid max-w-5xl gap-8 lg:grid-cols-[minmax(0,1fr)_320px]"><form onSubmit={save} className="border border-[var(--line)] bg-white p-6"><label className="mb-5 block text-sm">Business name<input name="business_name" defaultValue={code.business_name ?? ""} className="mt-2 block w-full border border-[var(--line)] px-3 py-3 outline-none focus:border-[var(--green)]" /></label><label className="mb-5 block text-sm">Google Maps review URL<input name="target_url" type="url" defaultValue={code.target_url ?? ""} placeholder="https://g.page/r/.../review" className="mt-2 block w-full border border-[var(--line)] px-3 py-3 outline-none focus:border-[var(--green)]" /></label><label className="block text-sm">Status<select name="status" defaultValue={code.status} className="mt-2 block w-full border border-[var(--line)] bg-white px-3 py-3"><option value="unassigned">Unassigned</option><option value="active">Active</option><option value="disabled">Disabled</option></select></label><button className="mt-8 bg-[var(--green)] px-5 py-3 text-sm font-semibold text-white">Save changes</button>{saved && <p className="mt-4 text-sm text-[var(--muted)]">{saved}</p>}</form><section><h2 className="mb-4 text-sm font-semibold">Scan history</h2><div className="border border-[var(--line)] bg-white">{events.length ? events.map(item => <div key={item.id} className="border-b border-[var(--line)] px-4 py-3 text-sm last:border-0"><p>{new Date(item.scanned_at).toLocaleString()}</p><p className="mt-1 truncate text-xs text-[var(--muted)]">{item.user_agent ?? "Unknown device"}</p></div>) : <p className="p-5 text-sm text-[var(--muted)]">No scans recorded.</p>}</div></section></div></div>;
}
